// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirpyredenable.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const chirpyRedEnable = `-- name: ChirpyRedEnable :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) ChirpyRedEnable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, chirpyRedEnable, id)
	return err
}
