// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: userlookup.sql

package database

import (
	"context"
)

const userLookup = `-- name: UserLookup :one
SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users
WHERE email = $1
`

func (q *Queries) UserLookup(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userLookup, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
